- name: "To install Pkgs"
  hosts: mylabservers
  become: true
  tasks: 
      - name: Remove apache httpd
        apt:
          name: apache2
          state: absent

      - name: Install apache httpd
        apt:
          name: apache2
          state: present
